/*
 * Copyright (C) 2020 CZ.NIC z.s.p.o. (http://www.nic.cz/)
 *
 * This is free software, licensed under the GNU General Public License v3.
 * See /LICENSE for more information.
 */

const wifiFixture1 = {
    devices: [
        {
            id: 0,
            enabled: false,
            SSID: "Turris - 1",
            channel: 36,
            hidden: false,
            hwmode: "11a",
            htmode: "VHT80",
            password: "12345678",
            guest_wifi: {
                enabled: false,
                SSID: "Turris-guest - 1",
                password: "01234567",
            },
            available_bands: [
                {
                    available_htmodes: ["NOHT", "HT20", "HT40"],
                    available_channels: [
                        { number: 1, frequency: 2412, radar: false },
                        { number: 2, frequency: 2417, radar: false },
                        { number: 3, frequency: 2422, radar: false },
                        { number: 4, frequency: 2427, radar: false },
                        { number: 5, frequency: 2432, radar: false },
                        { number: 6, frequency: 2437, radar: false },
                        { number: 7, frequency: 2442, radar: false },
                        { number: 8, frequency: 2447, radar: false },
                        { number: 9, frequency: 2452, radar: false },
                        { number: 10, frequency: 2457, radar: false },
                        { number: 11, frequency: 2462, radar: false },
                    ],
                    hwmode: "11g",
                },
                {
                    available_htmodes: [
                        "NOHT",
                        "HT20",
                        "HT40",
                        "VHT20",
                        "VHT40",
                        "VHT80",
                    ],
                    available_channels: [
                        { number: 36, frequency: 5180, radar: false },
                        { number: 40, frequency: 5200, radar: false },
                        { number: 44, frequency: 5220, radar: false },
                        { number: 48, frequency: 5240, radar: false },
                        { number: 52, frequency: 5260, radar: true },
                        { number: 56, frequency: 5280, radar: true },
                        { number: 60, frequency: 5300, radar: true },
                        { number: 64, frequency: 5320, radar: true },
                        { number: 100, frequency: 5500, radar: true },
                        { number: 104, frequency: 5520, radar: true },
                        { number: 108, frequency: 5540, radar: true },
                        { number: 112, frequency: 5560, radar: true },
                        { number: 116, frequency: 5580, radar: true },
                        { number: 120, frequency: 5600, radar: true },
                        { number: 124, frequency: 5620, radar: true },
                        { number: 128, frequency: 5640, radar: true },
                        { number: 132, frequency: 5660, radar: true },
                        { number: 136, frequency: 5680, radar: true },
                        { number: 140, frequency: 5700, radar: true },
                        { number: 144, frequency: 5720, radar: true },
                        { number: 149, frequency: 5745, radar: false },
                        { number: 153, frequency: 5765, radar: false },
                        { number: 157, frequency: 5785, radar: false },
                        { number: 161, frequency: 5805, radar: false },
                        { number: 165, frequency: 5825, radar: false },
                    ],
                    hwmode: "11a",
                },
            ],
        },
    ],
};

const wifiFixture2 = {
    devices: [
        {
            id: 0,
            enabled: false,
            SSID: "Turris - 1",
            channel: 36,
            hidden: false,
            hwmode: "11a",
            htmode: "VHT80",
            password: "12345678",
            guest_wifi: {
                enabled: false,
                SSID: "Turris-guest - 1",
                password: "01234567",
            },
            available_bands: [
                {
                    available_htmodes: ["NOHT", "HT20", "HT40"],
                    available_channels: [
                        { number: 1, frequency: 2412, radar: false },
                        { number: 2, frequency: 2417, radar: false },
                        { number: 3, frequency: 2422, radar: false },
                        { number: 4, frequency: 2427, radar: false },
                        { number: 5, frequency: 2432, radar: false },
                        { number: 6, frequency: 2437, radar: false },
                        { number: 7, frequency: 2442, radar: false },
                        { number: 8, frequency: 2447, radar: false },
                        { number: 9, frequency: 2452, radar: false },
                        { number: 10, frequency: 2457, radar: false },
                        { number: 11, frequency: 2462, radar: false },
                    ],
                    hwmode: "11g",
                },
                {
                    available_htmodes: [
                        "NOHT",
                        "HT20",
                        "HT40",
                        "VHT20",
                        "VHT40",
                        "VHT80",
                    ],
                    available_channels: [
                        { number: 36, frequency: 5180, radar: false },
                        { number: 40, frequency: 5200, radar: false },
                        { number: 44, frequency: 5220, radar: false },
                        { number: 48, frequency: 5240, radar: false },
                        { number: 52, frequency: 5260, radar: true },
                        { number: 56, frequency: 5280, radar: true },
                        { number: 60, frequency: 5300, radar: true },
                        { number: 64, frequency: 5320, radar: true },
                        { number: 100, frequency: 5500, radar: true },
                        { number: 104, frequency: 5520, radar: true },
                        { number: 108, frequency: 5540, radar: true },
                        { number: 112, frequency: 5560, radar: true },
                        { number: 116, frequency: 5580, radar: true },
                        { number: 120, frequency: 5600, radar: true },
                        { number: 124, frequency: 5620, radar: true },
                        { number: 128, frequency: 5640, radar: true },
                        { number: 132, frequency: 5660, radar: true },
                        { number: 136, frequency: 5680, radar: true },
                        { number: 140, frequency: 5700, radar: true },
                        { number: 144, frequency: 5720, radar: true },
                        { number: 149, frequency: 5745, radar: false },
                        { number: 153, frequency: 5765, radar: false },
                        { number: 157, frequency: 5785, radar: false },
                        { number: 161, frequency: 5805, radar: false },
                        { number: 165, frequency: 5825, radar: false },
                    ],
                    hwmode: "11a",
                },
            ],
        },
        {
            id: 1,
            enabled: false,
            SSID: "Turris - 2",
            channel: 36,
            hidden: false,
            hwmode: "11a",
            htmode: "VHT80",
            password: "12345678",
            guest_wifi: {
                enabled: false,
                SSID: "Turris-guest - 2",
                password: "01234567",
            },
            available_bands: [
                {
                    available_htmodes: ["NOHT", "HT20", "HT40"],
                    available_channels: [
                        { number: 1, frequency: 2412, radar: false },
                        { number: 2, frequency: 2417, radar: false },
                        { number: 3, frequency: 2422, radar: false },
                        { number: 4, frequency: 2427, radar: false },
                        { number: 5, frequency: 2432, radar: false },
                        { number: 6, frequency: 2437, radar: false },
                        { number: 7, frequency: 2442, radar: false },
                        { number: 8, frequency: 2447, radar: false },
                        { number: 9, frequency: 2452, radar: false },
                        { number: 10, frequency: 2457, radar: false },
                        { number: 11, frequency: 2462, radar: false },
                    ],
                    hwmode: "11g",
                },
                {
                    available_htmodes: [
                        "NOHT",
                        "HT20",
                        "HT40",
                        "VHT20",
                        "VHT40",
                        "VHT80",
                    ],
                    available_channels: [
                        { number: 36, frequency: 5180, radar: false },
                        { number: 40, frequency: 5200, radar: false },
                        { number: 44, frequency: 5220, radar: false },
                        { number: 48, frequency: 5240, radar: false },
                        { number: 52, frequency: 5260, radar: true },
                        { number: 56, frequency: 5280, radar: true },
                        { number: 60, frequency: 5300, radar: true },
                        { number: 64, frequency: 5320, radar: true },
                        { number: 100, frequency: 5500, radar: true },
                        { number: 104, frequency: 5520, radar: true },
                        { number: 108, frequency: 5540, radar: true },
                        { number: 112, frequency: 5560, radar: true },
                        { number: 116, frequency: 5580, radar: true },
                        { number: 120, frequency: 5600, radar: true },
                        { number: 124, frequency: 5620, radar: true },
                        { number: 128, frequency: 5640, radar: true },
                        { number: 132, frequency: 5660, radar: true },
                        { number: 136, frequency: 5680, radar: true },
                        { number: 140, frequency: 5700, radar: true },
                        { number: 144, frequency: 5720, radar: true },
                        { number: 149, frequency: 5745, radar: false },
                        { number: 153, frequency: 5765, radar: false },
                        { number: 157, frequency: 5785, radar: false },
                        { number: 161, frequency: 5805, radar: false },
                        { number: 165, frequency: 5825, radar: false },
                    ],
                    hwmode: "11a",
                },
            ],
        },
    ],
};

const wifiFixture3 = {
    devices: [
        {
            id: 0,
            enabled: false,
            SSID: "Turris - 1",
            channel: 36,
            hidden: false,
            hwmode: "11a",
            htmode: "VHT80",
            password: "12345678",
            guest_wifi: {
                enabled: false,
                SSID: "Turris-guest - 1",
                password: "01234567",
            },
            available_bands: [
                {
                    available_htmodes: ["NOHT", "HT20", "HT40"],
                    available_channels: [
                        { number: 1, frequency: 2412, radar: false },
                        { number: 2, frequency: 2417, radar: false },
                        { number: 3, frequency: 2422, radar: false },
                        { number: 4, frequency: 2427, radar: false },
                        { number: 5, frequency: 2432, radar: false },
                        { number: 6, frequency: 2437, radar: false },
                        { number: 7, frequency: 2442, radar: false },
                        { number: 8, frequency: 2447, radar: false },
                        { number: 9, frequency: 2452, radar: false },
                        { number: 10, frequency: 2457, radar: false },
                        { number: 11, frequency: 2462, radar: false },
                    ],
                    hwmode: "11g",
                },
                {
                    available_htmodes: [
                        "NOHT",
                        "HT20",
                        "HT40",
                        "VHT20",
                        "VHT40",
                        "VHT80",
                    ],
                    available_channels: [
                        { number: 36, frequency: 5180, radar: false },
                        { number: 40, frequency: 5200, radar: false },
                        { number: 44, frequency: 5220, radar: false },
                        { number: 48, frequency: 5240, radar: false },
                        { number: 52, frequency: 5260, radar: true },
                        { number: 56, frequency: 5280, radar: true },
                        { number: 60, frequency: 5300, radar: true },
                        { number: 64, frequency: 5320, radar: true },
                        { number: 100, frequency: 5500, radar: true },
                        { number: 104, frequency: 5520, radar: true },
                        { number: 108, frequency: 5540, radar: true },
                        { number: 112, frequency: 5560, radar: true },
                        { number: 116, frequency: 5580, radar: true },
                        { number: 120, frequency: 5600, radar: true },
                        { number: 124, frequency: 5620, radar: true },
                        { number: 128, frequency: 5640, radar: true },
                        { number: 132, frequency: 5660, radar: true },
                        { number: 136, frequency: 5680, radar: true },
                        { number: 140, frequency: 5700, radar: true },
                        { number: 144, frequency: 5720, radar: true },
                        { number: 149, frequency: 5745, radar: false },
                        { number: 153, frequency: 5765, radar: false },
                        { number: 157, frequency: 5785, radar: false },
                        { number: 161, frequency: 5805, radar: false },
                        { number: 165, frequency: 5825, radar: false },
                    ],
                    hwmode: "11a",
                },
            ],
        },
        {
            id: 1,
            enabled: false,
            SSID: "Turris - 2",
            channel: 36,
            hidden: false,
            hwmode: "11a",
            htmode: "VHT80",
            password: "12345678",
            guest_wifi: {
                enabled: false,
                SSID: "Turris-guest - 2",
                password: "01234567",
            },
            available_bands: [
                {
                    available_htmodes: ["NOHT", "HT20", "HT40"],
                    available_channels: [
                        { number: 1, frequency: 2412, radar: false },
                        { number: 2, frequency: 2417, radar: false },
                        { number: 3, frequency: 2422, radar: false },
                        { number: 4, frequency: 2427, radar: false },
                        { number: 5, frequency: 2432, radar: false },
                        { number: 6, frequency: 2437, radar: false },
                        { number: 7, frequency: 2442, radar: false },
                        { number: 8, frequency: 2447, radar: false },
                        { number: 9, frequency: 2452, radar: false },
                        { number: 10, frequency: 2457, radar: false },
                        { number: 11, frequency: 2462, radar: false },
                    ],
                    hwmode: "11g",
                },
                {
                    available_htmodes: [
                        "NOHT",
                        "HT20",
                        "HT40",
                        "VHT20",
                        "VHT40",
                        "VHT80",
                    ],
                    available_channels: [
                        { number: 36, frequency: 5180, radar: false },
                        { number: 40, frequency: 5200, radar: false },
                        { number: 44, frequency: 5220, radar: false },
                        { number: 48, frequency: 5240, radar: false },
                        { number: 52, frequency: 5260, radar: true },
                        { number: 56, frequency: 5280, radar: true },
                        { number: 60, frequency: 5300, radar: true },
                        { number: 64, frequency: 5320, radar: true },
                        { number: 100, frequency: 5500, radar: true },
                        { number: 104, frequency: 5520, radar: true },
                        { number: 108, frequency: 5540, radar: true },
                        { number: 112, frequency: 5560, radar: true },
                        { number: 116, frequency: 5580, radar: true },
                        { number: 120, frequency: 5600, radar: true },
                        { number: 124, frequency: 5620, radar: true },
                        { number: 128, frequency: 5640, radar: true },
                        { number: 132, frequency: 5660, radar: true },
                        { number: 136, frequency: 5680, radar: true },
                        { number: 140, frequency: 5700, radar: true },
                        { number: 144, frequency: 5720, radar: true },
                        { number: 149, frequency: 5745, radar: false },
                        { number: 153, frequency: 5765, radar: false },
                        { number: 157, frequency: 5785, radar: false },
                        { number: 161, frequency: 5805, radar: false },
                        { number: 165, frequency: 5825, radar: false },
                    ],
                    hwmode: "11a",
                },
            ],
        },
        {
            id: 2,
            enabled: false,
            SSID: "Turris - 3",
            channel: 36,
            hidden: false,
            hwmode: "11a",
            htmode: "VHT80",
            password: "12345678",
            guest_wifi: {
                enabled: false,
                SSID: "Turris-guest - 3",
                password: "01234567",
            },
            available_bands: [
                {
                    available_htmodes: ["NOHT", "HT20", "HT40"],
                    available_channels: [
                        { number: 1, frequency: 2412, radar: false },
                        { number: 2, frequency: 2417, radar: false },
                        { number: 3, frequency: 2422, radar: false },
                        { number: 4, frequency: 2427, radar: false },
                        { number: 5, frequency: 2432, radar: false },
                        { number: 6, frequency: 2437, radar: false },
                        { number: 7, frequency: 2442, radar: false },
                        { number: 8, frequency: 2447, radar: false },
                        { number: 9, frequency: 2452, radar: false },
                        { number: 10, frequency: 2457, radar: false },
                        { number: 11, frequency: 2462, radar: false },
                    ],
                    hwmode: "11g",
                },
                {
                    available_htmodes: [
                        "NOHT",
                        "HT20",
                        "HT40",
                        "VHT20",
                        "VHT40",
                        "VHT80",
                    ],
                    available_channels: [
                        { number: 36, frequency: 5180, radar: false },
                        { number: 40, frequency: 5200, radar: false },
                        { number: 44, frequency: 5220, radar: false },
                        { number: 48, frequency: 5240, radar: false },
                        { number: 52, frequency: 5260, radar: true },
                        { number: 56, frequency: 5280, radar: true },
                        { number: 60, frequency: 5300, radar: true },
                        { number: 64, frequency: 5320, radar: true },
                        { number: 100, frequency: 5500, radar: true },
                        { number: 104, frequency: 5520, radar: true },
                        { number: 108, frequency: 5540, radar: true },
                        { number: 112, frequency: 5560, radar: true },
                        { number: 116, frequency: 5580, radar: true },
                        { number: 120, frequency: 5600, radar: true },
                        { number: 124, frequency: 5620, radar: true },
                        { number: 128, frequency: 5640, radar: true },
                        { number: 132, frequency: 5660, radar: true },
                        { number: 136, frequency: 5680, radar: true },
                        { number: 140, frequency: 5700, radar: true },
                        { number: 144, frequency: 5720, radar: true },
                        { number: 149, frequency: 5745, radar: false },
                        { number: 153, frequency: 5765, radar: false },
                        { number: 157, frequency: 5785, radar: false },
                        { number: 161, frequency: 5805, radar: false },
                        { number: 165, frequency: 5825, radar: false },
                    ],
                    hwmode: "11a",
                },
            ],
        },
    ],
};

export { wifiFixture1, wifiFixture2, wifiFixture3 };
