export const TIMEZONES = {
    Africa: {
        CI: { Abidjan: ["Africa/Abidjan", "GMT0"] },
        GH: { Accra: ["Africa/Accra", "GMT0"] },
        ET: { "Addis Ababa": ["Africa/Addis Ababa", "EAT-3"] },
        DZ: { Algiers: ["Africa/Algiers", "CET-1"] },
        ER: { Asmara: ["Africa/Asmara", "EAT-3"] },
        ML: { Bamako: ["Africa/Bamako", "GMT0"] },
        CF: { Bangui: ["Africa/Bangui", "WAT-1"] },
        GM: { Banjul: ["Africa/Banjul", "GMT0"] },
        GW: { Bissau: ["Africa/Bissau", "GMT0"] },
        MW: { Blantyre: ["Africa/Blantyre", "CAT-2"] },
        CG: { Brazzaville: ["Africa/Brazzaville", "WAT-1"] },
        BI: { Bujumbura: ["Africa/Bujumbura", "CAT-2"] },
        EG: { Cairo: ["Africa/Cairo", "EET-2"] },
        MA: { Casablanca: ["Africa/Casablanca", "WET0WEST,M3.5.0,M10.5.0/3"] },
        ES: { Ceuta: ["Africa/Ceuta", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        GN: { Conakry: ["Africa/Conakry", "GMT0"] },
        SN: { Dakar: ["Africa/Dakar", "GMT0"] },
        TZ: { "Dar es Salaam": ["Africa/Dar es Salaam", "EAT-3"] },
        DJ: { Djibouti: ["Africa/Djibouti", "EAT-3"] },
        CM: { Douala: ["Africa/Douala", "WAT-1"] },
        EH: { "El Aaiun": ["Africa/El Aaiun", "WET0WEST,M3.5.0,M10.5.0/3"] },
        SL: { Freetown: ["Africa/Freetown", "GMT0"] },
        BW: { Gaborone: ["Africa/Gaborone", "CAT-2"] },
        ZW: { Harare: ["Africa/Harare", "CAT-2"] },
        ZA: { Johannesburg: ["Africa/Johannesburg", "SAST-2"] },
        SS: { Juba: ["Africa/Juba", "EAT-3"] },
        UG: { Kampala: ["Africa/Kampala", "EAT-3"] },
        SD: { Khartoum: ["Africa/Khartoum", "EAT-3"] },
        RW: { Kigali: ["Africa/Kigali", "CAT-2"] },
        CD: { Kinshasa: ["Africa/Kinshasa", "WAT-1"], Lubumbashi: ["Africa/Lubumbashi", "CAT-2"] },
        NG: { Lagos: ["Africa/Lagos", "WAT-1"] },
        GA: { Libreville: ["Africa/Libreville", "WAT-1"] },
        TG: { Lome: ["Africa/Lome", "GMT0"] },
        AO: { Luanda: ["Africa/Luanda", "WAT-1"] },
        ZM: { Lusaka: ["Africa/Lusaka", "CAT-2"] },
        GQ: { Malabo: ["Africa/Malabo", "WAT-1"] },
        MZ: { Maputo: ["Africa/Maputo", "CAT-2"] },
        LS: { Maseru: ["Africa/Maseru", "SAST-2"] },
        SZ: { Mbabane: ["Africa/Mbabane", "SAST-2"] },
        SO: { Mogadishu: ["Africa/Mogadishu", "EAT-3"] },
        LR: { Monrovia: ["Africa/Monrovia", "GMT0"] },
        KE: { Nairobi: ["Africa/Nairobi", "EAT-3"] },
        TD: { Ndjamena: ["Africa/Ndjamena", "WAT-1"] },
        NE: { Niamey: ["Africa/Niamey", "WAT-1"] },
        MR: { Nouakchott: ["Africa/Nouakchott", "GMT0"] },
        BF: { Ouagadougou: ["Africa/Ouagadougou", "GMT0"] },
        BJ: { "Porto-Novo": ["Africa/Porto-Novo", "WAT-1"] },
        ST: { "São Tomé": ["Africa/Sao Tome", "GMT0"] },
        LY: { Tripoli: ["Africa/Tripoli", "EET-2"] },
        TN: { Tunis: ["Africa/Tunis", "CET-1"] },
        NA: { Windhoek: ["Africa/Windhoek", "WAT-1WAST,M9.1.0,M4.1.0"] },
    },
    America: {
        US: {
            Adak: ["America/Adak", "HST10HDT,M3.2.0,M11.1.0"],
            Anchorage: ["America/Anchorage", "AKST9AKDT,M3.2.0,M11.1.0"],
            Boise: ["America/Boise", "MST7MDT,M3.2.0,M11.1.0"],
            Chicago: ["America/Chicago", "CST6CDT,M3.2.0,M11.1.0"],
            Denver: ["America/Denver", "MST7MDT,M3.2.0,M11.1.0"],
            Detroit: ["America/Detroit", "EST5EDT,M3.2.0,M11.1.0"],
            Indianapolis: ["America/Indiana/Indianapolis", "EST5EDT,M3.2.0,M11.1.0"],
            "Knox, Indiana": ["America/Indiana/Knox", "CST6CDT,M3.2.0,M11.1.0"],
            "Marengo, Indiana": ["America/Indiana/Marengo", "EST5EDT,M3.2.0,M11.1.0"],
            "Petersburg, Indiana": ["America/Indiana/Petersburg", "EST5EDT,M3.2.0,M11.1.0"],
            "Tell City, Indiana": ["America/Indiana/Tell City", "CST6CDT,M3.2.0,M11.1.0"],
            "Vevay, Indiana": ["America/Indiana/Vevay", "EST5EDT,M3.2.0,M11.1.0"],
            "Vincennes, Indiana": ["America/Indiana/Vincennes", "EST5EDT,M3.2.0,M11.1.0"],
            "Winamac, Indiana": ["America/Indiana/Winamac", "EST5EDT,M3.2.0,M11.1.0"],
            Juneau: ["America/Juneau", "AKST9AKDT,M3.2.0,M11.1.0"],
            Louisville: ["America/Kentucky/Louisville", "EST5EDT,M3.2.0,M11.1.0"],
            "Monticello, Kentucky": ["America/Kentucky/Monticello", "EST5EDT,M3.2.0,M11.1.0"],
            "Los Angeles": ["America/Los Angeles", "PST8PDT,M3.2.0,M11.1.0"],
            Menominee: ["America/Menominee", "CST6CDT,M3.2.0,M11.1.0"],
            Metlakatla: ["America/Metlakatla", "PST8"],
            "New York": ["America/New York", "EST5EDT,M3.2.0,M11.1.0"],
            Nome: ["America/Nome", "AKST9AKDT,M3.2.0,M11.1.0"],
            "Beulah, North Dakota": ["America/North Dakota/Beulah", "CST6CDT,M3.2.0,M11.1.0"],
            "Center, North Dakota": ["America/North Dakota/Center", "CST6CDT,M3.2.0,M11.1.0"],
            "New Salem, North Dakota": ["America/North Dakota/New Salem", "CST6CDT,M3.2.0,M11.1.0"],
            Phoenix: ["America/Phoenix", "MST7"],
            Sitka: ["America/Sitka", "AKST9AKDT,M3.2.0,M11.1.0"],
            Yakutat: ["America/Yakutat", "AKST9AKDT,M3.2.0,M11.1.0"],
        },
        AI: { Anguilla: ["America/Anguilla", "AST4"] },
        AG: { Antigua: ["America/Antigua", "AST4"] },
        BR: {
            Araguaina: ["America/Araguaina", "BRT3"],
            Bahia: ["America/Bahia", "BRT3"],
            Belem: ["America/Belem", "BRT3"],
            "Boa Vista": ["America/Boa Vista", "AMT4"],
            "Campo Grande": ["America/Campo Grande", "AMT4AMST,M10.3.0/0,M2.3.0/0"],
            Cuiaba: ["America/Cuiaba", "AMT4AMST,M10.3.0/0,M2.3.0/0"],
            Eirunepe: ["America/Eirunepe", "ACT5"],
            Fortaleza: ["America/Fortaleza", "BRT3"],
            Maceio: ["America/Maceio", "BRT3"],
            Manaus: ["America/Manaus", "AMT4"],
            Noronha: ["America/Noronha", "FNT2"],
            "Porto Velho": ["America/Porto Velho", "AMT4"],
            Recife: ["America/Recife", "BRT3"],
            "Rio Branco": ["America/Rio Branco", "ACT5"],
            Santarem: ["America/Santarem", "BRT3"],
            "Sao Paulo": ["America/Sao Paulo", "BRT3BRST,M10.3.0/0,M2.3.0/0"],
        },
        AR: {
            "Buenos Aires": ["America/Argentina/Buenos Aires", "ART3"],
            Catamarca: ["America/Argentina/Catamarca", "ART3"],
            Cordoba: ["America/Argentina/Cordoba", "ART3"],
            Jujuy: ["America/Argentina/Jujuy", "ART3"],
            "La Rioja": ["America/Argentina/La Rioja", "ART3"],
            Mendoza: ["America/Argentina/Mendoza", "ART3"],
            "Rio Gallegos": ["America/Argentina/Rio Gallegos", "ART3"],
            Salta: ["America/Argentina/Salta", "ART3"],
            "San Juan": ["America/Argentina/San Juan", "ART3"],
            "San Luis": ["America/Argentina/San Luis", "ART3"],
            Tucuman: ["America/Argentina/Tucuman", "ART3"],
            Ushuaia: ["America/Argentina/Ushuaia", "ART3"],
        },
        AW: { Aruba: ["America/Aruba", "AST4"] },
        PY: { Asunción: ["America/Asuncion", "PYT4PYST,M10.1.0/0,M3.4.0/0"] },
        CA: {
            Atikokan: ["America/Atikokan", "EST5"],
            "Blanc-Sablon": ["America/Blanc-Sablon", "AST4"],
            "Cambridge Bay": ["America/Cambridge Bay", "MST7MDT,M3.2.0,M11.1.0"],
            Creston: ["America/Creston", "MST7"],
            Dawson: ["America/Dawson", "PST8PDT,M3.2.0,M11.1.0"],
            "Dawson Creek": ["America/Dawson Creek", "MST7"],
            Edmonton: ["America/Edmonton", "MST7MDT,M3.2.0,M11.1.0"],
            "Fort Nelson": ["America/Fort Nelson", "MST7"],
            "Glace Bay": ["America/Glace Bay", "AST4ADT,M3.2.0,M11.1.0"],
            "Goose Bay": ["America/Goose Bay", "AST4ADT,M3.2.0,M11.1.0"],
            Halifax: ["America/Halifax", "AST4ADT,M3.2.0,M11.1.0"],
            Inuvik: ["America/Inuvik", "MST7MDT,M3.2.0,M11.1.0"],
            Iqaluit: ["America/Iqaluit", "EST5EDT,M3.2.0,M11.1.0"],
            Moncton: ["America/Moncton", "AST4ADT,M3.2.0,M11.1.0"],
            Nipigon: ["America/Nipigon", "EST5EDT,M3.2.0,M11.1.0"],
            Pangnirtung: ["America/Pangnirtung", "EST5EDT,M3.2.0,M11.1.0"],
            "Rainy River": ["America/Rainy River", "CST6CDT,M3.2.0,M11.1.0"],
            "Rankin Inlet": ["America/Rankin Inlet", "CST6CDT,M3.2.0,M11.1.0"],
            Regina: ["America/Regina", "CST6"],
            Resolute: ["America/Resolute", "CST6CDT,M3.2.0,M11.1.0"],
            "St. John’s": ["America/St Johns", "NST3:30NDT,M3.2.0,M11.1.0"],
            "Swift Current": ["America/Swift Current", "CST6"],
            "Thunder Bay": ["America/Thunder Bay", "EST5EDT,M3.2.0,M11.1.0"],
            Toronto: ["America/Toronto", "EST5EDT,M3.2.0,M11.1.0"],
            Vancouver: ["America/Vancouver", "PST8PDT,M3.2.0,M11.1.0"],
            Whitehorse: ["America/Whitehorse", "PST8PDT,M3.2.0,M11.1.0"],
            Winnipeg: ["America/Winnipeg", "CST6CDT,M3.2.0,M11.1.0"],
            Yellowknife: ["America/Yellowknife", "MST7MDT,M3.2.0,M11.1.0"],
        },
        MX: {
            "Bahia Banderas": ["America/Bahia Banderas", "CST6CDT,M4.1.0,M10.5.0"],
            Cancun: ["America/Cancun", "EST5"],
            Chihuahua: ["America/Chihuahua", "MST7MDT,M4.1.0,M10.5.0"],
            Hermosillo: ["America/Hermosillo", "MST7"],
            Matamoros: ["America/Matamoros", "CST6CDT,M3.2.0,M11.1.0"],
            Mazatlan: ["America/Mazatlan", "MST7MDT,M4.1.0,M10.5.0"],
            Merida: ["America/Merida", "CST6CDT,M4.1.0,M10.5.0"],
            "Mexico City": ["America/Mexico City", "CST6CDT,M4.1.0,M10.5.0"],
            Monterrey: ["America/Monterrey", "CST6CDT,M4.1.0,M10.5.0"],
            Ojinaga: ["America/Ojinaga", "MST7MDT,M3.2.0,M11.1.0"],
            "Santa Isabel": ["America/Santa Isabel", "PST8PDT,M4.1.0,M10.5.0"],
            Tijuana: ["America/Tijuana", "PST8PDT,M3.2.0,M11.1.0"],
        },
        BB: { Barbados: ["America/Barbados", "AST4"] },
        BZ: { Belize: ["America/Belize", "CST6"] },
        CO: { Bogota: ["America/Bogota", "COT5"] },
        VE: { Caracas: ["America/Caracas", "VET4:30"] },
        GF: { Cayenne: ["America/Cayenne", "GFT3"] },
        KY: { Cayman: ["America/Cayman", "EST5EDT,M3.2.0,M11.1.0"] },
        CR: { "Costa Rica": ["America/Costa Rica", "CST6"] },
        CW: { Curaçao: ["America/Curacao", "AST4"] },
        GL: {
            Danmarkshavn: ["America/Danmarkshavn", "GMT0"],
            Nuuk: ["America/Godthab", "WGT3WGST,M3.5.0/-2,M10.5.0/-1"],
            Ittoqqortoormiit: ["America/Scoresbysund", "EGT1EGST,M3.5.0/0,M10.5.0/1"],
            Thule: ["America/Thule", "AST4ADT,M3.2.0,M11.1.0"],
        },
        DM: { Dominica: ["America/Dominica", "AST4"] },
        SV: { "El Salvador": ["America/El Salvador", "CST6"] },
        TC: { "Grand Turk": ["America/Grand Turk", "AST4"] },
        GD: { Grenada: ["America/Grenada", "AST4"] },
        GP: { Guadeloupe: ["America/Guadeloupe", "AST4"] },
        GT: { Guatemala: ["America/Guatemala", "CST6"] },
        EC: { Guayaquil: ["America/Guayaquil", "ECT5"] },
        GY: { Guyana: ["America/Guyana", "GYT4"] },
        CU: { Havana: ["America/Havana", "CST5CDT,M3.2.0/0,M11.1.0/1"] },
        JM: { Jamaica: ["America/Jamaica", "EST5"] },
        BQ: { Kralendijk: ["America/Kralendijk", "AST4"] },
        BO: { "La Paz": ["America/La Paz", "BOT4"] },
        PE: { Lima: ["America/Lima", "PET5"] },
        SX: { "Lower Prince’s Quarter": ["America/Lower Princes", "AST4"] },
        NI: { Managua: ["America/Managua", "CST6"] },
        MF: { Marigot: ["America/Marigot", "AST4"] },
        MQ: { Martinique: ["America/Martinique", "AST4"] },
        PM: { Miquelon: ["America/Miquelon", "PMST3PMDT,M3.2.0,M11.1.0"] },
        UY: { Montevideo: ["America/Montevideo", "UYT3"] },
        MS: { Montserrat: ["America/Montserrat", "AST4"] },
        BS: { Nassau: ["America/Nassau", "EST5EDT,M3.2.0,M11.1.0"] },
        PA: { Panama: ["America/Panama", "EST5"] },
        SR: { Paramaribo: ["America/Paramaribo", "SRT3"] },
        TT: { "Port of Spain": ["America/Port of Spain", "AST4"] },
        HT: { "Port-au-Prince": ["America/Port-au-Prince", "EST5EDT,M3.2.0,M11.1.0"] },
        PR: { "Puerto Rico": ["America/Puerto Rico", "AST4"] },
        CL: { Santiago: ["America/Santiago", "CLT3"] },
        DO: { "Santo Domingo": ["America/Santo Domingo", "AST4"] },
        BL: { "St. Barthélemy": ["America/St Barthelemy", "AST4"] },
        KN: { "St. Kitts": ["America/St Kitts", "AST4"] },
        LC: { "St. Lucia": ["America/St Lucia", "AST4"] },
        VI: { "St. Thomas": ["America/St Thomas", "AST4"] },
        VC: { "St. Vincent": ["America/St Vincent", "AST4"] },
        HN: { Tegucigalpa: ["America/Tegucigalpa", "CST6"] },
        VG: { Tortola: ["America/Tortola", "AST4"] },
    },
    Antarctica: {
        AQ: {
            Casey: ["Antarctica/Casey", "AWST-8"],
            Davis: ["Antarctica/Davis", "DAVT-7"],
            "Dumont d’Urville": ["Antarctica/DumontDUrville", "DDUT-10"],
            Mawson: ["Antarctica/Mawson", "MAWT-5"],
            McMurdo: ["Antarctica/McMurdo", "NZST-12NZDT,M9.5.0,M4.1.0/3"],
            Palmer: ["Antarctica/Palmer", "CLT3"],
            Rothera: ["Antarctica/Rothera", "ROTT3"],
            Syowa: ["Antarctica/Syowa", "SYOT-3"],
            Troll: ["Antarctica/Troll", "UTC0CEST-2,M3.5.0/1,M10.5.0/3"],
            Vostok: ["Antarctica/Vostok", "VOST-6"],
        },
        AU: { "Macquarie Island": ["Antarctica/Macquarie", "MIST-11"] },
    },
    Arctic: { SJ: { Longyearbyen: ["Arctic/Longyearbyen", "CET-1CEST,M3.5.0,M10.5.0/3"] } },
    Asia: {
        YE: { Aden: ["Asia/Aden", "AST-3"] },
        KZ: {
            Almaty: ["Asia/Almaty", "ALMT-6"],
            Aqtau: ["Asia/Aqtau", "AQTT-5"],
            Aqtobe: ["Asia/Aqtobe", "AQTT-5"],
            Oral: ["Asia/Oral", "ORAT-5"],
            Qyzylorda: ["Asia/Qyzylorda", "QYZT-6"],
        },
        JO: { Amman: ["Asia/Amman", "EET-2EEST,M3.5.4/24,M10.5.5/1"] },
        RU: {
            Anadyr: ["Asia/Anadyr", "ANAT-12"],
            Chita: ["Asia/Chita", "IRKT-8"],
            Irkutsk: ["Asia/Irkutsk", "IRKT-8"],
            Kamchatka: ["Asia/Kamchatka", "PETT-12"],
            Khandyga: ["Asia/Khandyga", "YAKT-9"],
            Krasnoyarsk: ["Asia/Krasnoyarsk", "KRAT-7"],
            Magadan: ["Asia/Magadan", "MAGT-10"],
            Novokuznetsk: ["Asia/Novokuznetsk", "KRAT-7"],
            Novosibirsk: ["Asia/Novosibirsk", "NOVT-6"],
            Omsk: ["Asia/Omsk", "OMST-6"],
            Sakhalin: ["Asia/Sakhalin", "SAKT-10"],
            Srednekolymsk: ["Asia/Srednekolymsk", "SRET-11"],
            "Ust-Nera": ["Asia/Ust-Nera", "VLAT-10"],
            Vladivostok: ["Asia/Vladivostok", "VLAT-10"],
            Yakutsk: ["Asia/Yakutsk", "YAKT-9"],
            Yekaterinburg: ["Asia/Yekaterinburg", "YEKT-5"],
        },
        TM: { Ashgabat: ["Asia/Ashgabat", "TMT-5"] },
        IQ: { Baghdad: ["Asia/Baghdad", "AST-3"] },
        BH: { Bahrain: ["Asia/Bahrain", "AST-3"] },
        AZ: { Baku: ["Asia/Baku", "AZT-4AZST,M3.5.0/4,M10.5.0/5"] },
        TH: { Bangkok: ["Asia/Bangkok", "ICT-7"] },
        LB: { Beirut: ["Asia/Beirut", "EET-2EEST,M3.5.0/0,M10.5.0/0"] },
        KG: { Bishkek: ["Asia/Bishkek", "KGT-6"] },
        BN: { Brunei: ["Asia/Brunei", "BNT-8"] },
        MN: {
            Choibalsan: ["Asia/Choibalsan", "CHOT-8CHOST,M3.5.6,M9.5.6/0"],
            Hovd: ["Asia/Hovd", "HOVT-7HOVST,M3.5.6,M9.5.6/0"],
            Ulaanbaatar: ["Asia/Ulaanbaatar", "ULAT-8ULAST,M3.5.6,M9.5.6/0"],
        },
        LK: { Colombo: ["Asia/Colombo", "IST-5:30"] },
        SY: { Damascus: ["Asia/Damascus", "EET-2EEST,M3.5.5/0,M10.5.5/0"] },
        BD: { Dhaka: ["Asia/Dhaka", "BDT-6"] },
        TL: { Dili: ["Asia/Dili", "TLT-9"] },
        AE: { Dubai: ["Asia/Dubai", "GST-4"] },
        TJ: { Dushanbe: ["Asia/Dushanbe", "TJT-5"] },
        PS: {
            Gaza: ["Asia/Gaza", "EET-2EEST,M3.5.5/24,M10.3.6/144"],
            Hebron: ["Asia/Hebron", "EET-2EEST,M3.5.5/24,M10.3.6/144"],
        },
        VN: { "Ho Chi Minh City": ["Asia/Ho Chi Minh", "ICT-7"] },
        HK: { "Hong Kong": ["Asia/Hong Kong", "HKT-8"] },
        ID: {
            Jakarta: ["Asia/Jakarta", "WIB-7"],
            Jayapura: ["Asia/Jayapura", "WIT-9"],
            Makassar: ["Asia/Makassar", "WITA-8"],
            Pontianak: ["Asia/Pontianak", "WIB-7"],
        },
        IL: { Jerusalem: ["Asia/Jerusalem", "IST-2IDT,M3.4.4/26,M10.5.0"] },
        AF: { Kabul: ["Asia/Kabul", "AFT-4:30"] },
        PK: { Karachi: ["Asia/Karachi", "PKT-5"] },
        NP: { Kathmandu: ["Asia/Kathmandu", "NPT-5:45"] },
        IN: { Kolkata: ["Asia/Kolkata", "IST-5:30"] },
        MY: { "Kuala Lumpur": ["Asia/Kuala Lumpur", "MYT-8"], Kuching: ["Asia/Kuching", "MYT-8"] },
        KW: { Kuwait: ["Asia/Kuwait", "AST-3"] },
        MO: { Macau: ["Asia/Macau", "CST-8"] },
        PH: { Manila: ["Asia/Manila", "PHT-8"] },
        OM: { Muscat: ["Asia/Muscat", "GST-4"] },
        CY: { Nicosia: ["Asia/Nicosia", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        KH: { "Phnom Penh": ["Asia/Phnom Penh", "ICT-7"] },
        KP: { Pyongyang: ["Asia/Pyongyang", "KST-8:30"] },
        QA: { Qatar: ["Asia/Qatar", "AST-3"] },
        MM: { Yangon: ["Asia/Rangoon", "MMT-6:30"] },
        SA: { Riyadh: ["Asia/Riyadh", "AST-3"] },
        UZ: { Samarkand: ["Asia/Samarkand", "UZT-5"], Tashkent: ["Asia/Tashkent", "UZT-5"] },
        KR: { Seoul: ["Asia/Seoul", "KST-9"] },
        CN: { Shanghai: ["Asia/Shanghai", "CST-8"], Urumqi: ["Asia/Urumqi", "XJT-6"] },
        SG: { Singapore: ["Asia/Singapore", "SGT-8"] },
        TW: { Taipei: ["Asia/Taipei", "CST-8"] },
        GE: { Tbilisi: ["Asia/Tbilisi", "GET-4"] },
        BT: { Thimphu: ["Asia/Thimphu", "BTT-6"] },
        JP: { Tokyo: ["Asia/Tokyo", "JST-9"] },
        LA: { Vientiane: ["Asia/Vientiane", "ICT-7"] },
        AM: { Yerevan: ["Asia/Yerevan", "AMT-4"] },
    },
    Atlantic: {
        PT: {
            Azores: ["Atlantic/Azores", "AZOT1AZOST,M3.5.0/0,M10.5.0/1"],
            Madeira: ["Atlantic/Madeira", "WET0WEST,M3.5.0/1,M10.5.0"],
        },
        BM: { Bermuda: ["Atlantic/Bermuda", "AST4ADT,M3.2.0,M11.1.0"] },
        ES: { Canary: ["Atlantic/Canary", "WET0WEST,M3.5.0/1,M10.5.0"] },
        CV: { "Cape Verde": ["Atlantic/Cape Verde", "CVT1"] },
        FO: { Faroe: ["Atlantic/Faroe", "WET0WEST,M3.5.0/1,M10.5.0"] },
        IS: { Reykjavik: ["Atlantic/Reykjavik", "GMT0"] },
        GS: { "South Georgia": ["Atlantic/South Georgia", "GST2"] },
        SH: { "St. Helena": ["Atlantic/St Helena", "GMT0"] },
        FK: { Stanley: ["Atlantic/Stanley", "FKST3"] },
    },
    Australia: {
        AU: {
            Adelaide: ["Australia/Adelaide", "ACST-9:30ACDT,M10.1.0,M4.1.0/3"],
            Brisbane: ["Australia/Brisbane", "AEST-10"],
            "Broken Hill": ["Australia/Broken Hill", "ACST-9:30ACDT,M10.1.0,M4.1.0/3"],
            Currie: ["Australia/Currie", "AEST-10AEDT,M10.1.0,M4.1.0/3"],
            Darwin: ["Australia/Darwin", "ACST-9:30"],
            Eucla: ["Australia/Eucla", "ACWST-8:45"],
            Hobart: ["Australia/Hobart", "AEST-10AEDT,M10.1.0,M4.1.0/3"],
            Lindeman: ["Australia/Lindeman", "AEST-10"],
            "Lord Howe": ["Australia/Lord Howe", "LHST-10:30LHDT-11,M10.1.0,M4.1.0"],
            Melbourne: ["Australia/Melbourne", "AEST-10AEDT,M10.1.0,M4.1.0/3"],
            Perth: ["Australia/Perth", "AWST-8"],
            Sydney: ["Australia/Sydney", "AEST-10AEDT,M10.1.0,M4.1.0/3"],
        },
    },
    Europe: {
        NL: { Amsterdam: ["Europe/Amsterdam", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        AD: { Andorra: ["Europe/Andorra", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        GR: { Athens: ["Europe/Athens", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        RS: { Belgrade: ["Europe/Belgrade", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        DE: {
            Berlin: ["Europe/Berlin", "CET-1CEST,M3.5.0,M10.5.0/3"],
            Busingen: ["Europe/Busingen", "CET-1CEST,M3.5.0,M10.5.0/3"],
        },
        SK: { Bratislava: ["Europe/Bratislava", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        BE: { Brussels: ["Europe/Brussels", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        RO: { Bucharest: ["Europe/Bucharest", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        HU: { Budapest: ["Europe/Budapest", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        MD: { Chisinau: ["Europe/Chisinau", "EET-2EEST,M3.5.0,M10.5.0/3"] },
        DK: { Copenhagen: ["Europe/Copenhagen", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        IE: { Dublin: ["Europe/Dublin", "GMT0IST,M3.5.0/1,M10.5.0"] },
        GI: { Gibraltar: ["Europe/Gibraltar", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        GG: { Guernsey: ["Europe/Guernsey", "GMT0BST,M3.5.0/1,M10.5.0"] },
        FI: { Helsinki: ["Europe/Helsinki", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        IM: { "Isle of Man": ["Europe/Isle of Man", "GMT0BST,M3.5.0/1,M10.5.0"] },
        TR: { Istanbul: ["Europe/Istanbul", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        JE: { Jersey: ["Europe/Jersey", "GMT0BST,M3.5.0/1,M10.5.0"] },
        RU: {
            Kaliningrad: ["Europe/Kaliningrad", "EET-2"],
            Moscow: ["Europe/Moscow", "MSK-3"],
            Samara: ["Europe/Samara", "SAMT-4"],
            Simferopol: ["Europe/Simferopol", "MSK-3"],
            Volgograd: ["Europe/Volgograd", "MSK-3"],
        },
        UA: {
            Kiev: ["Europe/Kiev", "EET-2EEST,M3.5.0/3,M10.5.0/4"],
            Uzhhorod: ["Europe/Uzhgorod", "EET-2EEST,M3.5.0/3,M10.5.0/4"],
            Zaporozhye: ["Europe/Zaporozhye", "EET-2EEST,M3.5.0/3,M10.5.0/4"],
        },
        PT: { Lisbon: ["Europe/Lisbon", "WET0WEST,M3.5.0/1,M10.5.0"] },
        SI: { Ljubljana: ["Europe/Ljubljana", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        GB: { London: ["Europe/London", "GMT0BST,M3.5.0/1,M10.5.0"] },
        LU: { Luxembourg: ["Europe/Luxembourg", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        ES: { Madrid: ["Europe/Madrid", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        MT: { Malta: ["Europe/Malta", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        AX: { Mariehamn: ["Europe/Mariehamn", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        BY: { Minsk: ["Europe/Minsk", "MSK-3"] },
        MC: { Monaco: ["Europe/Monaco", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        NO: { Oslo: ["Europe/Oslo", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        FR: { Paris: ["Europe/Paris", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        ME: { Podgorica: ["Europe/Podgorica", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        CZ: { Prague: ["Europe/Prague", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        LV: { Riga: ["Europe/Riga", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        IT: { Rome: ["Europe/Rome", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        SM: { "San Marino": ["Europe/San Marino", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        BA: { Sarajevo: ["Europe/Sarajevo", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        MK: { Skopje: ["Europe/Skopje", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        BG: { Sofia: ["Europe/Sofia", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        SE: { Stockholm: ["Europe/Stockholm", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        EE: { Tallinn: ["Europe/Tallinn", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        AL: { Tirane: ["Europe/Tirane", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        LI: { Vaduz: ["Europe/Vaduz", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        VA: { Vatican: ["Europe/Vatican", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        AT: { Vienna: ["Europe/Vienna", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        LT: { Vilnius: ["Europe/Vilnius", "EET-2EEST,M3.5.0/3,M10.5.0/4"] },
        PL: { Warsaw: ["Europe/Warsaw", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        HR: { Zagreb: ["Europe/Zagreb", "CET-1CEST,M3.5.0,M10.5.0/3"] },
        CH: { Zurich: ["Europe/Zurich", "CET-1CEST,M3.5.0,M10.5.0/3"] },
    },
    Indian: {
        MG: { Antananarivo: ["Indian/Antananarivo", "EAT-3"] },
        IO: { Chagos: ["Indian/Chagos", "IOT-6"] },
        CX: { Christmas: ["Indian/Christmas", "CXT-7"] },
        CC: { Cocos: ["Indian/Cocos", "CCT-6:30"] },
        KM: { Comoro: ["Indian/Comoro", "EAT-3"] },
        TF: { Kerguelen: ["Indian/Kerguelen", "TFT-5"] },
        SC: { Mahe: ["Indian/Mahe", "SCT-4"] },
        MV: { Maldives: ["Indian/Maldives", "MVT-5"] },
        MU: { Mauritius: ["Indian/Mauritius", "MUT-4"] },
        YT: { Mayotte: ["Indian/Mayotte", "EAT-3"] },
        RE: { Réunion: ["Indian/Reunion", "RET-4"] },
    },
    Pacific: {
        WS: { Apia: ["Pacific/Apia", "WSST-13WSDT,M9.5.0/3,M4.1.0/4"] },
        NZ: {
            Auckland: ["Pacific/Auckland", "NZST-12NZDT,M9.5.0,M4.1.0/3"],
            Chatham: ["Pacific/Chatham", "CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45"],
        },
        PG: {
            "Bougainville Island": ["Pacific/Bougainville", "BST-11"],
            "Port Moresby": ["Pacific/Port Moresby", "PGT-10"],
        },
        FM: {
            Chuuk: ["Pacific/Chuuk", "CHUT-10"],
            Kosrae: ["Pacific/Kosrae", "KOST-11"],
            Pohnpei: ["Pacific/Pohnpei", "PONT-11"],
        },
        CL: { "Easter Island": ["Pacific/Easter", "EAST5"] },
        VU: { Efate: ["Pacific/Efate", "VUT-11"] },
        KI: {
            Enderbury: ["Pacific/Enderbury", "PHOT-13"],
            Kiritimati: ["Pacific/Kiritimati", "LINT-14"],
            Tarawa: ["Pacific/Tarawa", "GILT-12"],
        },
        TK: { Fakaofo: ["Pacific/Fakaofo", "TKT-13"] },
        FJ: { Fiji: ["Pacific/Fiji", "FJT-12FJST,M11.1.0,M1.3.0/3"] },
        TV: { Funafuti: ["Pacific/Funafuti", "TVT-12"] },
        EC: { Galapagos: ["Pacific/Galapagos", "GALT6"] },
        PF: {
            Gambier: ["Pacific/Gambier", "GAMT9"],
            Marquesas: ["Pacific/Marquesas", "MART9:30"],
            Tahiti: ["Pacific/Tahiti", "TAHT10"],
        },
        SB: { Guadalcanal: ["Pacific/Guadalcanal", "SBT-11"] },
        GU: { Guam: ["Pacific/Guam", "ChST-10"] },
        US: { Honolulu: ["Pacific/Honolulu", "HST10"], Johnston: ["Pacific/Johnston", "HST10"] },
        MH: { Kwajalein: ["Pacific/Kwajalein", "MHT-12"], Majuro: ["Pacific/Majuro", "MHT-12"] },
        UM: { Midway: ["Pacific/Midway", "SST11"], Wake: ["Pacific/Wake", "WAKT-12"] },
        NR: { Nauru: ["Pacific/Nauru", "NRT-12"] },
        NU: { Niue: ["Pacific/Niue", "NUT11"] },
        NF: { Norfolk: ["Pacific/Norfolk", "NFT-11"] },
        NC: { Noumea: ["Pacific/Noumea", "NCT-11"] },
        AS: { "Pago Pago": ["Pacific/Pago Pago", "SST11"] },
        PW: { Palau: ["Pacific/Palau", "PWT-9"] },
        PN: { Pitcairn: ["Pacific/Pitcairn", "PST8"] },
        CK: { Rarotonga: ["Pacific/Rarotonga", "CKT10"] },
        MP: { Saipan: ["Pacific/Saipan", "ChST-10"] },
        TO: { Tongatapu: ["Pacific/Tongatapu", "TOT-13"] },
        WF: { Wallis: ["Pacific/Wallis", "WFT-12"] },
    },
};
export const COUNTRIES = {
    CI: "Côte d’Ivoire",
    GH: "Ghana",
    ET: "Ethiopia",
    DZ: "Algeria",
    ER: "Eritrea",
    ML: "Mali",
    CF: "Central African Republic",
    GM: "Gambia",
    GW: "Guinea-Bissau",
    MW: "Malawi",
    CG: "Congo - Brazzaville",
    BI: "Burundi",
    EG: "Egypt",
    MA: "Morocco",
    ES: "Spain",
    GN: "Guinea",
    SN: "Senegal",
    TZ: "Tanzania",
    DJ: "Djibouti",
    CM: "Cameroon",
    EH: "Western Sahara",
    SL: "Sierra Leone",
    BW: "Botswana",
    ZW: "Zimbabwe",
    ZA: "South Africa",
    SS: "South Sudan",
    UG: "Uganda",
    SD: "Sudan",
    RW: "Rwanda",
    CD: "Congo - Kinshasa",
    NG: "Nigeria",
    GA: "Gabon",
    TG: "Togo",
    AO: "Angola",
    ZM: "Zambia",
    GQ: "Equatorial Guinea",
    MZ: "Mozambique",
    LS: "Lesotho",
    SZ: "Swaziland",
    SO: "Somalia",
    LR: "Liberia",
    KE: "Kenya",
    TD: "Chad",
    NE: "Niger",
    MR: "Mauritania",
    BF: "Burkina Faso",
    BJ: "Benin",
    ST: "São Tomé & Príncipe",
    LY: "Libya",
    TN: "Tunisia",
    NA: "Namibia",
    US: "United States",
    AI: "Anguilla",
    AG: "Antigua & Barbuda",
    BR: "Brazil",
    AR: "Argentina",
    AW: "Aruba",
    PY: "Paraguay",
    CA: "Canada",
    MX: "Mexico",
    BB: "Barbados",
    BZ: "Belize",
    CO: "Colombia",
    VE: "Venezuela",
    GF: "French Guiana",
    KY: "Cayman Islands",
    CR: "Costa Rica",
    CW: "Curaçao",
    GL: "Greenland",
    DM: "Dominica",
    SV: "El Salvador",
    TC: "Turks & Caicos Islands",
    GD: "Grenada",
    GP: "Guadeloupe",
    GT: "Guatemala",
    EC: "Ecuador",
    GY: "Guyana",
    CU: "Cuba",
    JM: "Jamaica",
    BQ: "Caribbean Netherlands",
    BO: "Bolivia",
    PE: "Peru",
    SX: "Sint Maarten",
    NI: "Nicaragua",
    MF: "St. Martin",
    MQ: "Martinique",
    PM: "St. Pierre & Miquelon",
    UY: "Uruguay",
    MS: "Montserrat",
    BS: "Bahamas",
    PA: "Panama",
    SR: "Suriname",
    TT: "Trinidad & Tobago",
    HT: "Haiti",
    PR: "Puerto Rico",
    CL: "Chile",
    DO: "Dominican Republic",
    BL: "St. Barthélemy",
    KN: "St. Kitts & Nevis",
    LC: "St. Lucia",
    VI: "U.S. Virgin Islands",
    VC: "St. Vincent & Grenadines",
    HN: "Honduras",
    VG: "British Virgin Islands",
    AQ: "Antarctica",
    AU: "Australia",
    SJ: "Svalbard & Jan Mayen",
    YE: "Yemen",
    KZ: "Kazakhstan",
    JO: "Jordan",
    RU: "Russia",
    TM: "Turkmenistan",
    IQ: "Iraq",
    BH: "Bahrain",
    AZ: "Azerbaijan",
    TH: "Thailand",
    LB: "Lebanon",
    KG: "Kyrgyzstan",
    BN: "Brunei",
    MN: "Mongolia",
    LK: "Sri Lanka",
    SY: "Syria",
    BD: "Bangladesh",
    TL: "Timor-Leste",
    AE: "United Arab Emirates",
    TJ: "Tajikistan",
    PS: "Palestinian Territories",
    VN: "Vietnam",
    HK: "Hong Kong SAR China",
    ID: "Indonesia",
    IL: "Israel",
    AF: "Afghanistan",
    PK: "Pakistan",
    NP: "Nepal",
    IN: "India",
    MY: "Malaysia",
    KW: "Kuwait",
    MO: "Macau SAR China",
    PH: "Philippines",
    OM: "Oman",
    CY: "Cyprus",
    KH: "Cambodia",
    KP: "North Korea",
    QA: "Qatar",
    MM: "Myanmar (Burma)",
    SA: "Saudi Arabia",
    UZ: "Uzbekistan",
    KR: "South Korea",
    CN: "China",
    SG: "Singapore",
    TW: "Taiwan",
    GE: "Georgia",
    BT: "Bhutan",
    JP: "Japan",
    LA: "Laos",
    AM: "Armenia",
    PT: "Portugal",
    BM: "Bermuda",
    CV: "Cape Verde",
    FO: "Faroe Islands",
    IS: "Iceland",
    GS: "South Georgia & South Sandwich Islands",
    SH: "St. Helena",
    FK: "Falkland Islands",
    NL: "Netherlands",
    AD: "Andorra",
    GR: "Greece",
    RS: "Serbia",
    DE: "Germany",
    SK: "Slovakia",
    BE: "Belgium",
    RO: "Romania",
    HU: "Hungary",
    MD: "Moldova",
    DK: "Denmark",
    IE: "Ireland",
    GI: "Gibraltar",
    GG: "Guernsey",
    FI: "Finland",
    IM: "Isle of Man",
    TR: "Turkey",
    JE: "Jersey",
    UA: "Ukraine",
    SI: "Slovenia",
    GB: "United Kingdom",
    LU: "Luxembourg",
    MT: "Malta",
    AX: "Åland Islands",
    BY: "Belarus",
    MC: "Monaco",
    NO: "Norway",
    FR: "France",
    ME: "Montenegro",
    CZ: "Czech Republic",
    LV: "Latvia",
    IT: "Italy",
    SM: "San Marino",
    BA: "Bosnia & Herzegovina",
    MK: "Macedonia",
    BG: "Bulgaria",
    SE: "Sweden",
    EE: "Estonia",
    AL: "Albania",
    LI: "Liechtenstein",
    VA: "Vatican City",
    AT: "Austria",
    LT: "Lithuania",
    PL: "Poland",
    HR: "Croatia",
    CH: "Switzerland",
    MG: "Madagascar",
    IO: "British Indian Ocean Territory",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands",
    KM: "Comoros",
    TF: "French Southern Territories",
    SC: "Seychelles",
    MV: "Maldives",
    MU: "Mauritius",
    YT: "Mayotte",
    RE: "Réunion",
    WS: "Samoa",
    NZ: "New Zealand",
    PG: "Papua New Guinea",
    FM: "Micronesia",
    VU: "Vanuatu",
    KI: "Kiribati",
    TK: "Tokelau",
    FJ: "Fiji",
    TV: "Tuvalu",
    PF: "French Polynesia",
    SB: "Solomon Islands",
    GU: "Guam",
    MH: "Marshall Islands",
    UM: "U.S. Outlying Islands",
    NR: "Nauru",
    NU: "Niue",
    NF: "Norfolk Island",
    NC: "New Caledonia",
    AS: "American Samoa",
    PW: "Palau",
    PN: "Pitcairn Islands",
    CK: "Cook Islands",
    MP: "Northern Mariana Islands",
    TO: "Tonga",
    WF: "Wallis & Futuna",
};
